### ISSUE TITLE
Starting from 1.5.0-alpha.14, not compatible with asciidoctor-gradle-plugin

### ISSUE THREAD

**Issue by smartg00se** [asciidoctor/asciidoctorj-pdf#15]
1.5.0-alpha.11 works fine. starting from 1.5.0-alpha.14, gradle fails with:

Unable to load class 'org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor'.

I've tried asciidoctor-gradle-plugin 1.5.3 and 1.5.7, the results holds.

**Comment by robertpanzer** [comment]
Please attach any logs that you have. 
Also it looks like you are using Spring Restdocs. 
They recently made a new release that fixed a problem with pdf. Please check that you have the latest version.

**Comment by smartg00se** [comment]
Yes I'am using spring-rest-doc 2.0.0.release, which is the latest stable release. The logs:


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctor'.
> (NameError) cannot load Java class org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctor'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.jruby.exceptions.RaiseException: (NameError) cannot load Java class org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor
	at org.jruby.javasupport.JavaClass.for_name(org/jruby/javasupport/JavaClass.java:286)
	at org.jruby.javasupport.JavaUtilities.get_proxy_class(org/jruby/javasupport/JavaUtilities.java:34)
	at RUBY.block in java_import(uri:classloader:/jruby/java/core_ext/object.rb:49)
	at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2486)
	at RUBY.java_import(uri:classloader:/jruby/java/core_ext/object.rb:36)
	at RUBY.<main>(<script>:1)
Caused by: java.lang.ClassNotFoundException: org.springframework.restdocs.asciidoctor.DefaultAttributesPreprocessor
	at org.jruby.javasupport.JavaSupportImpl.loadJavaClass(JavaSupportImpl.java:154)
	at org.jruby.javasupport.JavaSupportImpl.loadJavaClassVerbose(JavaSupportImpl.java:163)
	at org.jruby.javasupport.JavaClass.forNameVerbose(JavaClass.java:271)
	at org.jruby.javasupport.JavaClass.for_name(JavaClass.java:286)
	at org.jruby.javasupport.Java.get_proxy_class(Java.java:386)
	at org.jruby.javasupport.JavaUtilities.get_proxy_class(JavaUtilities.java:34)
	at org.jruby.javasupport.JavaUtilities$INVOKER$s$1$0$get_proxy_class.call(JavaUtilities$INVOKER$s$1$0$get_proxy_class.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:182)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:111)
	at org.jruby.runtime.Block.yield(Block.java:167)
	at org.jruby.RubyArray.collect(RubyArray.java:2472)
	at org.jruby.RubyArray.map19(RubyArray.java:2486)
	at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(RubyArray$INVOKER$i$0$0$map19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:497)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:298)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:355)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
	at org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:186)
	at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:173)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:479)
	at org.jruby.Ruby.evalScriptlet(Ruby.java:455)
	at org.asciidoctor.extension.JavaExtensionRegistry.javaImport(JavaExtensionRegistry.java:218)
	at org.asciidoctor.extension.JavaExtensionRegistry.preprocessor(JavaExtensionRegistry.java:49)
	at org.springframework.restdocs.asciidoctor.RestDocsExtensionRegistry.register(RestDocsExtensionRegistry.java:32)
	at org.asciidoctor.extension.internal.ExtensionRegistryExecutor.registerAllExtensions(ExtensionRegistryExecutor.java:21)
	at org.asciidoctor.internal.JRubyAsciidoctor.registerExtensions(JRubyAsciidoctor.java:96)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:63)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:54)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:668)
	at org.asciidoctor.Asciidoctor$Factory$create.call(Unknown Source)
	at org.asciidoctor.gradle.AsciidoctorTask.withAsciidoctor(AsciidoctorTask.groovy:877)
	at org.asciidoctor.gradle.AsciidoctorTask.processAsciidocSources(AsciidoctorTask.groovy:584)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

**Comment by robertpanzer** [comment]
Can you provide an example that allows to reproduce the problem?

**Comment by smartg00se** [comment]
Bellow is my build.gradle (It works).  If I update the org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11 to 1.5.0-alpha.14, the above error will occur.
-------------------------------------------------------------------------------------------------------------------
buildscript {
	ext {
		springBootVersion = '1.5.10.RELEASE'
        swagger2markupVersion = '1.3.1'
	}
	repositories {
		mavenCentral()
        maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
        jcenter()
        mavenLocal()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")

        classpath "io.github.swagger2markup:swagger2markup-spring-restdocs-ext:${swagger2markupVersion}"
        classpath "io.github.swagger2markup:swagger2markup-gradle-plugin:${swagger2markupVersion}"

        classpath "org.asciidoctor:asciidoctor-gradle-plugin:1.5.7"
        classpath "org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.11"    // do not update this!!!
	}
}

plugins {
	id "org.asciidoctor.convert" version "1.5.7"
	id "com.gorylenko.gradle-git-properties" version "1.4.21"
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'war'
apply plugin: 'io.github.swagger2markup'
apply plugin: 'io.spring.dependency-management'


version = '0.0.6'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
    jcenter()
    maven { url 'https://repo.spring.io/snapshot' }
    mavenLocal()
}


ext {
	springCloudVersion = ' Edgware.SR2.RELEASE'
    restAssuredVersion = '3.0.7'
    springfoxVersion = '2.8.0'

    asciiDocOutputDir = file("${buildDir}/asciidoc/generated")  // swagger2markup generated .adoc goes here
    swaggerOutputDir = file("${buildDir}/swagger")
    snippetsOutputDir = file("${buildDir}/generated-snippets")   // rest docs snippets dir.
}

ext['spring-restdocs.version'] = '2.0.0.RELEASE'

//springBoot {
//	buildInfo()
//}

dependencies {

    // an asciidoctor extension
    // set the snippets attribute to "build/generated_snippets"(hardcoded) in the .adoc files.
	asciidoctor "org.springframework.restdocs:spring-restdocs-asciidoctor:${project.ext['spring-restdocs.version']}"

	compile'org.springframework.boot:spring-boot-starter-actuator'
	compile'org.springframework.boot:spring-boot-actuator-docs'

	compile 'org.springframework.boot:spring-boot-starter-web'
	compile 'org.apache.httpcomponents:httpasyncclient'
	compile 'com.google.guava:guava:24.0-jre'
	compile 'com.google.code.gson:gson'

	runtime'org.springframework.boot:spring-boot-devtools'

    // Use testNg instead of junit
	compileOnly('org.projectlombok:lombok')

	testCompile('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'junit', module: 'junit;'
	}
    testCompile "org.testng:testng:6.14.2"


    // swagger
    compile "io.swagger:swagger-annotations:1.5.18"		// do not update this!
    compile "io.springfox:springfox-swagger2:${springfoxVersion}"
    compile "io.springfox:springfox-swagger-ui:${springfoxVersion}"
    testCompile "io.springfox:springfox-bean-validators:${springfoxVersion}"

	// rest assured
    testCompile "io.rest-assured:rest-assured:${restAssuredVersion}"
	testCompile "io.rest-assured:json-schema-validator:${restAssuredVersion}"
//    testCompile "io.rest-assured:spring-mock-mvc:${restAssuredVersion}"

    // spring rest docs
	testCompile "org.springframework.restdocs:spring-restdocs-restassured"
}

ext {
	snippetsDir = file("${buildDir}/generated-snippets")
}

test {
	useTestNG()
	outputs.dir snippetsDir

    systemProperty 'io.springfox.staticdocs.outputDir', swaggerOutputDir
    systemProperty 'io.springfox.staticdocs.snippetsOutputDir', snippetsOutputDir   // needed. set the {snippets} in .adoc
    systemProperty 'io.springfox.staticdocs.asciiDocOutputDir',asciiDocOutputDir
}


convertSwagger2markup {
    dependsOn test
    swaggerInput "${swaggerOutputDir}/swagger.json"
    outputDir asciiDocOutputDir
    config = [
            'swagger2markup.pathsGroupedBy' : 'TAGS',
//            'swagger2markup.extensions.springRestDocs.snippetBaseUri': snippetsOutputDir.getAbsolutePath()
    ]
}

//asciidoctor {
//	inputs.dir snippetsDir
//	dependsOn test
//}

asciidoctor {
    dependsOn convertSwagger2markup
    inputs.dir snippetsDir
//    dependsOn test
    sources {
        include 'index.adoc'
    }
    backends = ['html5', 'pdf']
    attributes = [
            doctype: 'book',
            toc: 'left',
            toclevels: '3',
            numbered: '',
            sectlinks: '',
            sectanchors: '',
            hardbreaks: '',
            generated: asciiDocOutputDir
    ]
}

**Comment by robertpanzer** [comment]
Sorry, I haven't done anything yet with Spring Restdocs.
To analyze this I would need some kind of project that I can clone and just build.

**Comment by Fleshgrinder** [comment]
I have the exact same problem.

**Comment by bric3** [comment]
For reference I have the same issue https://github.com/asciidoctor/asciidoctorj/issues/661, this very same error happened when upgrading asciidoctorj-diagram to 1.5.9, reverting to 1.5.8 prevented the issue.

Not related I'm not using Spring Boot 2.0 (Spring Boot 1.5.8, Spring Rest Doc 1.2.4), I'm not using asciidoctor-pdf either.

**Comment by mojavelinux** [comment]
This issue either has to do with AsciidoctorJ or the Gradle plugin. I would recommend starting with the Gradle plugin since it could have to do with how it sets up the classpath. If it turns out to be AsciidoctorJ, then the issue can be moved there.

Therefore, I'm going to transfer this issue.
